{{ config(materialized='view',schema='stg')}}
Select
	[EntryNo] as [EntryNo_] ,
	[G_LAccountNo] as [G_LAccountNo_] ,
	[DocumentNo] as [DocumentNo_] ,
	[Description] ,
	[Bal_AccountNo] as [Bal_AccountNo_] ,
	[No_Series] ,
	[TaxAreaCode] ,
	[TaxGroupCode] ,
	[VATBus_PostingGroup] ,
	[VATProd_PostingGroup] ,
	[ICPartnerCode] ,
	[JournalBatchName] ,
	[ReasonCode] ,
	[Gen_Bus_PostingGroup] ,
	[Gen_Prod_PostingGroup] ,
	[ExternalDocumentNo] as [ExternalDocumentNo_] ,
	[SourceNo] as [SourceNo_] ,
	[GlobalDimension1Code] ,
	[GlobalDimension2Code] ,
	[UserID] ,
	[SourceCode] ,
	[JobNo] as [JobNo_] ,
	[BusinessUnitCode] ,
	[Prod_OrderNo] as [Prod_OrderNo_] ,
	[STETransactionID] ,
	[systemId] as [$systemId] ,
	[systemCreatedBy] as [$systemCreatedBy] ,
	[systemModifiedBy] as [$systemModifiedBy] ,
	[timestamp] ,
	[DocumentType] ,
	[System_CreatedEntry] as [System-CreatedEntry] ,
	[Amount] ,
	[Add__CurrencyCreditAmount] as [Add_-CurrencyCreditAmount] ,
	[Quantity] ,
	[VATAmount] ,
	[DebitAmount] ,
	[CreditAmount] ,
	[Additional_CurrencyAmount] as [Additional-CurrencyAmount] ,
	[Add__CurrencyDebitAmount] as [Add_-CurrencyDebitAmount] ,
	[PostingDate] ,
	[DocumentDate] ,
	[LastModifiedDateTime] ,
	[systemCreatedAt] as [$systemCreatedAt] ,
	[systemModifiedAt] as [$systemModifiedAt] ,
	[FAEntryType] ,
	[FAEntryNo] as [FAEntryNo_] ,
	[GST_HST] ,
	[UseTax] ,
	[CloseIncomeStatementDim_ID] ,
	[Reversed] ,
	[ReversedbyEntryNo] as [ReversedbyEntryNo_] ,
	[ReversedEntryNo] as [ReversedEntryNo_] ,
	[DimensionSetID] ,
	[Prior_YearEntry] as [Prior-YearEntry] ,
	[Gen_PostingType] ,
	[Bal_AccountType] ,
	[TransactionNo] as [TransactionNo_] ,
	[SourceType] ,
	[TaxLiable] 
From stg.[BC_BJAuctionCompany_GLEntry_0972_Incr] 
Where [dbt_valid_to] is null