{{ config(materialized='view',schema='stg')}}
Select
	[No] as [No_] ,
	[systemId] as [$systemId] ,
	[EORINumber] ,
	[MobilePhoneNo] as [MobilePhoneNo_] ,
	[systemCreatedBy] as [$systemCreatedBy] ,
	[systemModifiedBy] as [$systemModifiedBy] ,
	[TaxAreaID] ,
	[ContactID] ,
	[ContactGraphId] ,
	[CFDIPurpose] ,
	[CFDIRelation] ,
	[Ship_toCode] as [Ship-toCode] ,
	[Image] ,
	[Id] ,
	[CurrencyId] ,
	[PaymentTermsId] ,
	[ShipmentMethodId] ,
	[PaymentMethodId] ,
	[TaxExemptionNo] as [TaxExemptionNo_] ,
	[RFCNo] as [RFCNo_] ,
	[CURPNo] as [CURPNo_] ,
	[StateInscription] ,
	[DocumentSendingProfile] ,
	[GLN] ,
	[ResponsibilityCenter] ,
	[ShippingTime] ,
	[ShippingAgentServiceCode] ,
	[ServiceZoneCode] ,
	[BaseCalendarCode] ,
	[UPSZone] ,
	[TaxAreaCode] ,
	[VATBus_PostingGroup] ,
	[ICPartnerCode] ,
	[PreferredBankAccountCode] ,
	[CashFlowPaymentTermsCode] ,
	[PrimaryContactNo] as [PrimaryContactNo_] ,
	[PostCode] ,
	[County] ,
	[E_Mail] as [E-Mail] ,
	[HomePage] ,
	[ReminderTermsCode] ,
	[No_Series] ,
	[PaymentMethodCode] ,
	[LocationCode] ,
	[FaxNo] as [FaxNo_] ,
	[TelexAnswerBack] ,
	[VATRegistrationNo] as [VATRegistrationNo_] ,
	[Gen_Bus_PostingGroup] ,
	[PlaceofExport] ,
	[InvoiceDisc_Code] ,
	[CustomerDisc_Group] ,
	[Country_RegionCode] ,
	[CollectionMethod] ,
	[Bill_toCustomerNo] as [Bill-toCustomerNo_] ,
	[LanguageCode] ,
	[PaymentTermsCode] ,
	[Fin_ChargeTermsCode] ,
	[SalespersonCode] ,
	[ShipmentMethodCode] ,
	[ShippingAgentCode] ,
	[GlobalDimension1Code] ,
	[GlobalDimension2Code] ,
	[ChainName] ,
	[CustomerPostingGroup] ,
	[CurrencyCode] ,
	[CustomerPriceGroup] ,
	[City] ,
	[Contact] ,
	[PhoneNo] as [PhoneNo_] ,
	[TelexNo] as [TelexNo_] ,
	[OurAccountNo] as [OurAccountNo_] ,
	[TerritoryCode] ,
	[Name] ,
	[SearchName] ,
	[Name2] ,
	[Address] ,
	[Address2] ,
	[timestamp] ,
	[Picture] ,
	[BudgetedAmount] ,
	[CreditLimitLCY] ,
	[Amount] ,
	[Prepayment] as [Prepayment_] ,
	[StatisticsGroup] ,
	[Blocked] ,
	[ContactType] ,
	[ValidateEUVatReg_No] as [ValidateEUVatReg_No_] ,
	[PrivacyBlocked] ,
	[DisableSearchbyName] ,
	[UseGLNinElectronicDocument] ,
	[PriceCalculationMethod] ,
	[AllowLineDisc] as [AllowLineDisc_] ,
	[CopySell_toAddr_toQteFrom] as [CopySell-toAddr_toQteFrom] ,
	[BankCommunication] ,
	[CheckDateFormat] ,
	[CheckDateSeparator] ,
	[TaxIdentificationType] ,
	[CombineShipments] ,
	[TaxLiable] ,
	[Reserve] ,
	[BlockPaymentTolerance] ,
	[PartnerType] ,
	[ShippingAdvice] ,
	[InvoiceCopies] ,
	[LastStatementNo] as [LastStatementNo_] ,
	[PrintStatements] ,
	[Priority] ,
	[ApplicationMethod] ,
	[PricesIncludingVAT] ,
	[LastDateModified] ,
	[LastModifiedDateTime] ,
	[systemCreatedAt] as [$systemCreatedAt] ,
	[systemModifiedAt] as [$systemModifiedAt] 
From stg.[BC_BJAuctionCompany_Customer_0972_Incr] 
Where [dbt_valid_to] is null