{{ config(materialized='view',schema='stg')}}
Select
	[No] as [No_] ,
	[Buy_fromVendorNo] as [Buy-fromVendorNo_] ,
	[systemId] as [$systemId] ,
	[systemCreatedBy] as [$systemCreatedBy] ,
	[systemModifiedBy] as [$systemModifiedBy] ,
	[Ship_toUPSZone] as [Ship-toUPSZone] ,
	[TaxExemptionNo] as [TaxExemptionNo_] ,
	[ProvincialTaxAreaCode] ,
	[STETransactionID] ,
	[IRS1099Code] ,
	[FiscalInvoiceNumberPAC] ,
	[CampaignNo] as [CampaignNo_] ,
	[Buy_fromContactNo] as [Buy-fromContactNo_] ,
	[Pay_toContactNo] as [Pay-toContactNo_] ,
	[ResponsibilityCenter] ,
	[ReturnOrderNo] as [ReturnOrderNo_] ,
	[ReturnOrderNo_Series] ,
	[UserID] ,
	[SourceCode] ,
	[TaxAreaCode] ,
	[VATBus_PostingGroup] ,
	[Prepmt_Cr_MemoNo_Series] ,
	[PrepaymentOrderNo] as [PrepaymentOrderNo_] ,
	[Area] ,
	[TransactionSpecification] ,
	[PaymentMethodCode] ,
	[Pre_AssignedNo_Series] as [Pre-AssignedNo_Series] ,
	[No_Series] ,
	[Pre_AssignedNo] as [Pre-AssignedNo_] ,
	[Buy_fromCountry_RegionCode] as [Buy-fromCountry_RegionCode] ,
	[Ship_toPostCode] as [Ship-toPostCode] ,
	[Ship_toCounty] as [Ship-toCounty] ,
	[Ship_toCountry_RegionCode] as [Ship-toCountry_RegionCode] ,
	[OrderAddressCode] ,
	[EntryPoint] ,
	[Buy_fromContact] as [Buy-fromContact] ,
	[Pay_toPostCode] as [Pay-toPostCode] ,
	[Pay_toCounty] as [Pay-toCounty] ,
	[Pay_toCountry_RegionCode] as [Pay-toCountry_RegionCode] ,
	[Buy_fromPostCode] as [Buy-fromPostCode] ,
	[Buy_fromCounty] as [Buy-fromCounty] ,
	[VATCountry_RegionCode] ,
	[Buy_fromVendorName] as [Buy-fromVendorName] ,
	[Buy_fromVendorName2] as [Buy-fromVendorName2] ,
	[Buy_fromAddress] as [Buy-fromAddress] ,
	[Buy_fromAddress2] as [Buy-fromAddress2] ,
	[Buy_fromCity] as [Buy-fromCity] ,
	[VATRegistrationNo] as [VATRegistrationNo_] ,
	[Sell_toCustomerNo] as [Sell-toCustomerNo_] ,
	[ReasonCode] ,
	[Gen_Bus_PostingGroup] ,
	[TransactionType] ,
	[TransportMethod] ,
	[LanguageCode] ,
	[PurchaserCode] ,
	[OnHold] ,
	[Applies_toDoc_No] as [Applies-toDoc_No_] ,
	[Bal_AccountNo] as [Bal_AccountNo_] ,
	[VendorCr_MemoNo] as [VendorCr_MemoNo_] ,
	[LocationCode] ,
	[ShortcutDimension1Code] ,
	[ShortcutDimension2Code] ,
	[VendorPostingGroup] ,
	[CurrencyCode] ,
	[InvoiceDisc_Code] ,
	[Ship_toAddress2] as [Ship-toAddress2] ,
	[Ship_toCity] as [Ship-toCity] ,
	[Ship_toContact] as [Ship-toContact] ,
	[PostingDescription] ,
	[PaymentTermsCode] ,
	[ShipmentMethodCode] ,
	[Pay_toContact] as [Pay-toContact] ,
	[YourReference] ,
	[Ship_toCode] as [Ship-toCode] ,
	[Ship_toName] as [Ship-toName] ,
	[Ship_toName2] as [Ship-toName2] ,
	[Ship_toAddress] as [Ship-toAddress] ,
	[Pay_toVendorNo] as [Pay-toVendorNo_] ,
	[Pay_toName] as [Pay-toName] ,
	[Pay_toName2] as [Pay-toName2] ,
	[Pay_toAddress] as [Pay-toAddress] ,
	[Pay_toAddress2] as [Pay-toAddress2] ,
	[Pay_toCity] as [Pay-toCity] ,
	[timestamp] ,
	[PaymentDiscount] as [PaymentDiscount_] ,
	[CurrencyFactor] ,
	[VATBaseDiscount] as [VATBaseDiscount_] ,
	[systemModifiedAt] as [$systemModifiedAt] ,
	[PostingDate] ,
	[ExpectedReceiptDate] ,
	[DueDate] ,
	[Pmt_DiscountDate] ,
	[DocumentDate] ,
	[systemCreatedAt] as [$systemCreatedAt] ,
	[PricesIncludingVAT] ,
	[No_Printed] ,
	[Applies_toDoc_Type] as [Applies-toDoc_Type] ,
	[PriceCalculationMethod] ,
	[Bal_AccountType] ,
	[Correction] ,
	[TaxLiable] ,
	[PrepaymentCreditMemo] ,
	[DimensionSetID] ,
	[VendorLedgerEntryNo] as [VendorLedgerEntryNo_] 
From stg.[BC_BJAuctionCompany_PurchCrMemoHdr_0972_Incr] 
Where [dbt_valid_to] is null