{{ config(materialized='view',schema='stg')}}
Select
	[No] as [No_] ,
	[LastDateModified] ,
	[LastModifiedDateTime] ,
	[systemCreatedAt] as [$systemCreatedAt] ,
	[systemModifiedAt] as [$systemModifiedAt] ,
	[AccountType] ,
	[Income_Balance] ,
	[Debit_Credit] ,
	[Blocked] ,
	[DirectPosting] ,
	[ReconciliationAccount] ,
	[TaxLiable] ,
	[ExchangeRateAdjustment] ,
	[AccountCategory] ,
	[OmitDefaultDescr_inJnl] as [OmitDefaultDescr_inJnl_] ,
	[AccountSubcategoryEntryNo] as [AccountSubcategoryEntryNo_] ,
	[APIAccountType] ,
	[NewPage] ,
	[No_ofBlankLines] ,
	[Indentation] ,
	[Consol_TranslationMethod] ,
	[Gen_PostingType] ,
	[AutomaticExt_Texts] ,
	[timestamp] ,
	[Picture] ,
	[Name] ,
	[SearchName] ,
	[GlobalDimension1Code] ,
	[GlobalDimension2Code] ,
	[No_2] ,
	[DefaultDeferralTemplateCode] ,
	[Id] ,
	[SATAccountCode] ,
	[systemId] as [$systemId] ,
	[systemCreatedBy] as [$systemCreatedBy] ,
	[systemModifiedBy] as [$systemModifiedBy] ,
	[TaxGroupCode] ,
	[VATBus_PostingGroup] ,
	[VATProd_PostingGroup] ,
	[DefaultICPartnerG_LAcc_No] ,
	[CostTypeNo] as [CostTypeNo_] ,
	[GIFICode] ,
	[Totaling] ,
	[Consol_DebitAcc] as [Consol_DebitAcc_] ,
	[Consol_CreditAcc] as [Consol_CreditAcc_] ,
	[Gen_Bus_PostingGroup] ,
	[Gen_Prod_PostingGroup] ,
	[TaxAreaCode] 
From stg.[BC_BJAuctionCompany_GLAccount_0972_Incr] 
Where [dbt_valid_to] is null