{{ config(materialized='view',schema='stg')}}
Select
	[No] as [No_] ,
	[PriceUnitConversion] ,
	[Type] ,
	[AllowInvoiceDisc] as [AllowInvoiceDisc_] ,
	[Critical] ,
	[SalesBlocked] ,
	[PurchasingBlocked] ,
	[ReorderingPolicy] ,
	[IncludeInventory] ,
	[ManufacturingPolicy] ,
	[CreatedFromNonstockItem] ,
	[UseCross_Docking] as [UseCross-Docking] ,
	[OrderTrackingPolicy] ,
	[AssemblyPolicy] ,
	[Low_LevelCode] as [Low-LevelCode] ,
	[InventoryValueZero] ,
	[DiscreteOrderQuantity] ,
	[FlushingMethod] ,
	[ReplenishmentSystem] ,
	[Blocked] ,
	[PriceIncludesVAT] ,
	[AutomaticExt_Texts] ,
	[Reserve] ,
	[StockoutWarning] ,
	[PreventNegativeInventory] ,
	[StatisticsGroup] ,
	[CommissionGroup] ,
	[Price_ProfitCalculation] ,
	[CostingMethod] ,
	[CostisAdjusted] ,
	[AllowOnlineAdjustment] ,
	[LastDateTimeModified] ,
	[LastDateModified] ,
	[LastTimeModified] ,
	[LastUnitCostCalc_Date] ,
	[LastCountingPeriodUpdate] ,
	[NextCountingStartDate] ,
	[NextCountingEndDate] ,
	[systemCreatedAt] as [$systemCreatedAt] ,
	[systemModifiedAt] as [$systemModifiedAt] ,
	[UnitPrice] ,
	[Profit] as [Profit_] ,
	[UnitCost] ,
	[StandardCost] ,
	[LastDirectCost] ,
	[OverflowLevel] ,
	[Single_LevelMaterialCost] as [Single-LevelMaterialCost] ,
	[Single_LevelCapacityCost] as [Single-LevelCapacityCost] ,
	[Single_LevelSubcontrd_Cost] as [Single-LevelSubcontrd_Cost] ,
	[Single_LevelCap_OvhdCost] as [Single-LevelCap_OvhdCost] ,
	[Single_LevelMfg_OvhdCost] as [Single-LevelMfg_OvhdCost] ,
	[MinimumOrderQuantity] ,
	[MaximumOrderQuantity] ,
	[SafetyStockQuantity] ,
	[OrderMultiple] ,
	[RoundingPrecision] ,
	[DampenerQuantity] ,
	[BudgetedAmount] ,
	[BudgetProfit] ,
	[LotSize] ,
	[Rolled_upMaterialCost] as [Rolled-upMaterialCost] ,
	[Rolled_upCapacityCost] as [Rolled-upCapacityCost] ,
	[Scrap] as [Scrap_] ,
	[GrossWeight] ,
	[NetWeight] ,
	[UnitsperParcel] ,
	[UnitVolume] ,
	[DutyUnitConversion] ,
	[BudgetQuantity] ,
	[IndirectCost] as [IndirectCost_] ,
	[ReorderPoint] ,
	[MaximumInventory] ,
	[ReorderQuantity] ,
	[UnitListPrice] ,
	[DutyDue] as [DutyDue_] ,
	[OverheadRate] ,
	[Rolled_upSubcontractedCost] as [Rolled-upSubcontractedCost] ,
	[Rolled_upMfg_OvhdCost] as [Rolled-upMfg_OvhdCost] ,
	[Rolled_upCap_OverheadCost] as [Rolled-upCap_OverheadCost] ,
	[timestamp] ,
	[SATItemClassification] ,
	[RoutingNo] as [RoutingNo_] ,
	[ProductionBOMNo] as [ProductionBOMNo_] ,
	[CommonItemNo] as [CommonItemNo_] ,
	[ItemCategoryId] ,
	[systemId] as [$systemId] ,
	[Put_awayUnitofMeasureCode] as [Put-awayUnitofMeasureCode] ,
	[PhysInvtCountingPeriodCode] ,
	[Id] ,
	[UnitofMeasureId] ,
	[TaxGroupId] ,
	[DutyClass] ,
	[ItemTrackingCode] ,
	[LotNos] as [LotNos_] ,
	[ExpirationCalculation] ,
	[WarehouseClassCode] ,
	[SpecialEquipmentCode] ,
	[Put_awayTemplateCode] as [Put-awayTemplateCode] ,
	[LotAccumulationPeriod] ,
	[DampenerPeriod] ,
	[ManufacturerCode] ,
	[ItemCategoryCode] ,
	[ProductGroupCode] ,
	[ServiceItemGroup] ,
	[SerialNos] as [SerialNos_] ,
	[SafetyLeadTime] ,
	[SalesUnitofMeasure] ,
	[Purch_UnitofMeasure] ,
	[TimeBucket] ,
	[ReschedulingPeriod] ,
	[VATProd_PostingGroup] ,
	[GlobalDimension1Code] ,
	[GlobalDimension2Code] ,
	[ApplicationWksh_UserID] ,
	[GTIN] ,
	[DefaultDeferralTemplateCode] ,
	[VATBus_PostingGr_Price] ,
	[Gen_Prod_PostingGroup] ,
	[Picture] ,
	[Country_RegionofOriginCode] ,
	[No_Series] ,
	[TaxGroupCode] ,
	[DutyCode] ,
	[Durability] ,
	[FreightType] ,
	[TariffNo] as [TariffNo_] ,
	[Country_RegionPurchasedCode] ,
	[BlockReason] ,
	[ShelfNo] as [ShelfNo_] ,
	[ItemDisc_Group] ,
	[VendorNo] as [VendorNo_] ,
	[VendorItemNo] as [VendorItemNo_] ,
	[LeadTimeCalculation] ,
	[AlternativeItemNo] as [AlternativeItemNo_] ,
	[No_2] ,
	[Description] ,
	[SearchDescription] ,
	[Description2] ,
	[BaseUnitofMeasure] ,
	[InventoryPostingGroup] ,
	[PurchasingCode] ,
	[Over_ReceiptCode] as [Over-ReceiptCode] ,
	[systemCreatedBy] as [$systemCreatedBy] ,
	[systemModifiedBy] as [$systemModifiedBy] 
From stg.[BC_BJAuctionCompany_Item_0972_Incr] 
Where [dbt_valid_to] is null