{{ config(materialized='table',schema='stg')}}
SELECT
	[Id] AS [InvoiceID],
	[PayerId] AS [PayerID],
	[OwnerId] AS [OwnerID],
	[CreatedOn] AS [CreatedDate],
	[UpdatedOn] AS [UpdatedDate],
	[DeletedOn] AS [DeletedDate],
	[Status],
	[CreatedDTTM],
	[FulfilledDTTM],
	[Comments] AS [Comment],
	[LastUpdatedUser],
	[Currency],
	[Type],
	[ShippingAmount],
	[Subtotal],
	[Total],
	[ShippingFirstName],
	[ShippingLastName],
	[ShippingStreet1],
	[ShippingStreet2],
	[ShippingCity],
	[ShippingStateRegion] AS [ShippingState],
	[ShippingZipPostal] AS [ShippingPostalCode],
	[ShippingCountry],
	[BIllingFIrstName] AS [BillingFIrstName],
	[BillingLastName],
	[BillingStreet1],
	[BillingStreet2],
	[BillingCity],
	[BillingStateRegion] AS [BillingState],
	[BillingZIpPostal] AS [BillingPostalCode],
	[BillingCountry],
	[SalesTax],
	[PaidDTTM],
	[IsPayerLocked],
	[Shipped] AS [HasShipped],
	[ShippingDetails],
	[BuyersPremiumPercent] AS [BuyerPremiumPct],
	[BuyersPremiumAmount] AS [BuyerPremiumAmount],
	[IsArchived]
FROM [stg].[AH_Invoices_FinalView];