{{ config(materialized='table',schema='stg')}}
SELECT
		[Id] AS [LineItemsID],
		[OwnerId] AS [OwnerID],
		[PayerId] AS [PayerID],
		[InvoiceId] AS [InvoiceID],
		[ListingId] AS [ListingID],
		[Description],
		[LastUpdatedUser],
		[Currency],
		[Status],
		[Type],
		[TotalAmount],
		[Quantity] AS [QTY],
		[PerUnitAmount],
		[Taxable] AS [IsTaxable],
		[IsArchived],
		[Relistiteration],
		[BuyersPremiumApplies] AS [HasBuyerPremiumApplies],
		[IsPayerArchived],
		[DateStamp],
		[CreatedOn] AS [CreatedDate],
		[UpdatedOn] AS [UpdatedDate],
		[DeletedOn] AS [DeletedDate]
FROM [stg].[AH_LineItems_FinalView];