{{ config(materialized='table',schema='stg')}}
-- Auct_CA_Auct_Customer_CTE1
    SELECT 
        addrmrg.[CustomerAccountID],
        addrmrg.[CurrentCompanyID],
        addrmrg.[AddressID],
        addrmrg.[HomeAddress], 
        addrmrg.[BusinessAddress], 
        addrmrg.[LocalAddress], 
        addrmrg.[DealerAddress], 
        addrmrg.[MailingAddress],
        addrmrg.[City],
        addrmrg.[State],
        addrmrg.[PostalCode],
        addrmrg.[Country],
        addrmrg.[AddressStatus],
        addrmrg.[IsDefaultAddress],
        addrmrg.[IsActiveAddress],
        addrmrg.[EffectiveStartDate] as [add_EffectiveStartDate],
        addrmrg.[EffectiveEndDate] as [add_EffectiveEndDate],
        emailmrg.[ContactID],
        emailmrg.[EmailAddress],
        emailmrg.[IsActiveEmail],
        emailmrg.[EmailBlastOptIn],
        emailmrg.[EffectiveStartDate] as [email_EffectiveStartDate],
        emailmrg.[EffectiveEndDate] as [email_EffectiveEndDate],
        phmrg.[MobilePhone_PhoneID], 
        phmrg.[MobilePhone_PhoneNumber], 
        phmrg.[MobilePhone_PhoneStatus], 
        phmrg.[IsDefaultMobilePhone], 
        phmrg.[IsActiveMobilePhone], 
        phmrg.[DirectPhone_PhoneID], 
        phmrg.[DirectPhone_PhoneNumber], 
        phmrg.[DirectPhone_PhoneStatus],
        phmrg.[IsDefaultDirectPhone],  
        phmrg.[IsActiveDirectPhone],  
        phmrg.[HomePhone_PhoneID],
        phmrg.[HomePhone_PhoneNumber], 
        phmrg.[HomePhone_PhoneStatus],  
        phmrg.[IsDefaultHomePhone],  
        phmrg.[IsActiveHomePhone],  
        phmrg.[HomeFax_PhoneID],  
        phmrg.[HomeFax_PhoneNumber], 
        phmrg.[HomeFax_PhoneStatus],  
        phmrg.[IsDefaultHomeFax],  
        phmrg.[IsActiveHomeFax],  
        phmrg.[DealerMobile_PhoneID],  
        phmrg.[DealerMobile_PhoneNumber], 
        phmrg.[DealerMobile_PhoneStatus],  
        phmrg.[IsDefaultDealerMobile],  
        phmrg.[IsActiveDealerMobile],  
        phmrg.[DealerPhone_PhoneID],  
        phmrg.[DealerPhone_PhoneNumber], 
        phmrg.[DealerPhone_PhoneStatus],  
        phmrg.[IsDefaultDealerPhone],  
        phmrg.[IsActiveDealerPhone],  
        phmrg.[DealerFax_PhoneID],  
        phmrg.[DealerFax_PhoneNumber], 
        phmrg.[DealerFax_PhoneStatus],  
        phmrg.[IsDefaultDealerFax],  
        phmrg.[IsActiveDealerFax],  
        phmrg.[BusinessPhone_PhoneID],  
        phmrg.[BusinessPhone_PhoneNumber], 
        phmrg.[BusinessPhone_PhoneStatus],  
        phmrg.[IsDefaultBusinessPhone],  
        phmrg.[IsActiveBusinessPhone],  
        phmrg.[BusinessFax_PhoneID],  
        phmrg.[BusinessFax_PhoneNumber], 
        phmrg.[BusinessFax_PhoneStatus],  
        phmrg.[IsDefaultBusinessFax],  
        phmrg.[IsActiveBusinessFax],  
        phmrg.[BusinessMobile_PhoneID],  
        phmrg.[BusinessMobile_PhoneNumber], 
        phmrg.[BusinessMobile_PhoneStatus],  
        phmrg.[IsDefaultBusinessMobile],  
        phmrg.[IsActiveBusinessMobile], 
        phmrg.[VendorPhone_PhoneID],  
        phmrg.[VendorPhone_PhoneNumber], 
        phmrg.[VendorPhone_PhoneStatus],  
        phmrg.[IsDefaultVendorPhone],      
        phmrg.[IsActiveVendorPhone],  
        phmrg.[VendorFax_PhoneID],  
        phmrg.[VendorFax_PhoneNumber], 
        phmrg.[VendorFax_PhoneStatus],  
        phmrg.[IsDefaultVendorFax],  
        phmrg.[IsActiveVendorFax],  
        phmrg.[RequestNumber_PhoneID],  
        phmrg.[RequestNumber_PhoneNumber], 
        phmrg.[RequestNumber_PhoneStatus],  
        phmrg.[IsDefaultRequestNumber],  
        phmrg.[IsActiveRequestNumber],  
        phmrg.[RequestFax_PhoneID],  
        phmrg.[RequestFax_PhoneNumber],
        phmrg.[RequestFax_PhoneStatus],
        phmrg.[IsDefaultRequestFax],
        phmrg.[IsActiveRequestFax],
        phmrg.[LocalPhone_PhoneID],
        phmrg.[LocalPhone_PhoneNumber],
        phmrg.[LocalPhone_PhoneStatus], 
        phmrg.[IsDefaultLocalPhone],
        phmrg.[IsActiveLocalPhone], 
        phmrg.[Pager_PhoneID],
        phmrg.[Pager_PhoneNumber], 
        phmrg.[Pager_PhoneStatus],  
        phmrg.[IsDefaultPager],
        phmrg.[IsActivePager],
        phmrg.[UnknownPhoneType_PhoneID],
        phmrg.[UnknownPhoneType_PhoneNumber], 
        phmrg.[UnknownPhoneType_PhoneStatus],  
        phmrg.[IsDefaultUnknownPhoneType],
        phmrg.[IsActiveUnknownPhoneType],
        phmrg.[EffectiveStartDate] as [phone_EffectiveStartDate],
        phmrg.[EffectiveEndDate] as [phone_EffectiveEndDate]
    FROM [stg].[Auct_Address_Merge_NoNull] addrmrg
    LEFT JOIN [stg].[Auct_Email_Merge_NoNull] emailmrg
        ON addrmrg.[CustomerAccountID]=emailmrg.[CustomerAccountID]
    LEFT JOIN [stg].[Auct_Phone_Merge_NoNull] phmrg
        ON addrmrg.[CustomerAccountID]=phmrg.[CustomerAccountID]
