{{ config(materialized='table',schema='dbo')}}
Select
	cast([Approved] as bit) [Approved],
	cast([ID] as int) [Id],
	cast([InvoiceID] as int) [InvoiceId],
	cast([CreatedOn] as datetime) [CreatedOn],
	cast([UpdatedOn] as datetime) [UpdatedOn],
	cast([DeletedOn] as datetime) [DeletedOn],
	cast([DaTestamp] as datetime) [DateStamp],
	cast([Amount] as numeric(19,4)) [Amount],
	cast([AuthorizationCode] as nvarchar(4000)) [AuthorizationCode],
	cast([AvsResponseCode] as nvarchar(4000)) [AVSResponseCode],
	cast([Cvv2ResponseCode] as nvarchar(4000)) [CVV2ResponseCode],
	cast([CavResponseCode] as nvarchar(4000)) [CAVResponseCode],
	cast([BuyerStreet] as nvarchar(4000)) [BuyerStreet],
	cast([BuyerCity] as nvarchar(4000)) [BuyerCity],
	cast([ResponseStatus] as nvarchar(4000)) [ResponseStatus],
	cast([ProvIDEr] as nvarchar(4000)) [Provider],
	cast([RawResponseCode] as nvarchar(4000)) [RawResponseCode],
	cast([Description] as nvarchar(4000)) [Description],
	cast([TransactionID] as nvarchar(4000)) [TransactionID],
	cast([Method] as nvarchar(4000)) [Method],
	cast([BuyerStateregion] as nvarchar(4000)) [BuyerStateRegion],
	cast([BuyerzipPostal] as nvarchar(4000)) [BuyerZipPostal],
	cast([BuyerEmail] as nvarchar(4000)) [BuyerEmail],
	cast([AllFields] as nvarchar(4000)) [AllFields],
	cast([LastUpdatedUser] as nvarchar(4000)) [LastUpdatedUser] 
From stg.[AH_PaymentResponses_FinalView]