{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	cast([ShippingAgentServiceCode] as nvarchar(4000)) [ShippingAgentServiceCode],
	cast([DraftCr_MemoSystemId] as nvarchar(4000)) [DraftCr_MemoSystemId],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy],
	cast([Sell-toE-Mail] as nvarchar(4000)) [Sell_toE_Mail],
	cast([CFDIPurpose] as nvarchar(4000)) [CFDIPurpose],
	cast([CFDIRelation] as nvarchar(4000)) [CFDIRelation],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([ShippingAgentCode] as nvarchar(4000)) [ShippingAgentCode],
	cast([PackageTrackingNo_] as nvarchar(4000)) [PackageTrackingNo],
	cast([ErrorCode] as nvarchar(4000)) [ErrorCode],
	cast([ErrorDescription] as nvarchar(4000)) [ErrorDescription],
	cast([PACWebServiceName] as nvarchar(4000)) [PACWebServiceName],
	cast([FiscalInvoiceNumberPAC] as nvarchar(4000)) [FiscalInvoiceNumberPAC],
	cast([Date_TimeFirstReq_Sent] as nvarchar(4000)) [Date_TimeFirstReq_Sent],
	cast([Sell-toPhoneNo_] as nvarchar(4000)) [Sell_toPhoneNo],
	cast([TaxExemptionNo_] as nvarchar(4000)) [TaxExemptionNo],
	cast([STETransactionID] as nvarchar(4000)) [STETransactionID],
	cast([CertificateSerialNo_] as nvarchar(4000)) [CertificateSerialNo],
	cast([Date_TimeStamped] as nvarchar(4000)) [Date_TimeStamped],
	cast([Date_TimeSent] as nvarchar(4000)) [Date_TimeSent],
	cast([Date_TimeCanceled] as nvarchar(4000)) [Date_TimeCanceled],
	cast([OpportunityNo_] as nvarchar(4000)) [OpportunityNo],
	cast([ResponsibilityCenter] as nvarchar(4000)) [ResponsibilityCenter],
	cast([ReturnOrderNo_] as nvarchar(4000)) [ReturnOrderNo],
	cast([ReturnOrderNo_Series] as nvarchar(4000)) [ReturnOrderNo_Series],
	cast([Id] as nvarchar(4000)) [Id],
	cast([Ship-toUPSZone] as nvarchar(4000)) [Ship_toUPSZone],
	cast([PrepaymentOrderNo_] as nvarchar(4000)) [PrepaymentOrderNo],
	cast([DocumentExchangeIdentifier] as nvarchar(4000)) [DocumentExchangeIdentifier],
	cast([Doc_Exch_OriginalIdentifier] as nvarchar(4000)) [Doc_Exch_OriginalIdentifier],
	cast([CampaignNo_] as nvarchar(4000)) [CampaignNo],
	cast([Sell-toContactNo_] as nvarchar(4000)) [Sell_toContactNo],
	cast([Bill-toContactNo_] as nvarchar(4000)) [Bill_toContactNo],
	cast([Pre-AssignedNo_] as nvarchar(4000)) [Pre_AssignedNo],
	cast([UserID] as nvarchar(4000)) [UserID],
	cast([SourceCode] as nvarchar(4000)) [SourceCode],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([Prepmt_Cr_MemoNo_Series] as nvarchar(4000)) [Prepmt_Cr_MemoNo_Series],
	cast([ExternalDocumentNo_] as nvarchar(4000)) [ExternalDocumentNo],
	cast([Area] as nvarchar(4000)) [Area],
	cast([TransactionSpecification] as nvarchar(4000)) [TransactionSpecification],
	cast([PaymentMethodCode] as nvarchar(4000)) [PaymentMethodCode],
	cast([Pre-AssignedNo_Series] as nvarchar(4000)) [Pre_AssignedNo_Series],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([Sell-toCounty] as nvarchar(4000)) [Sell_toCounty],
	cast([Sell-toCountry_RegionCode] as nvarchar(4000)) [Sell_toCountry_RegionCode],
	cast([Ship-toPostCode] as nvarchar(4000)) [Ship_toPostCode],
	cast([Ship-toCounty] as nvarchar(4000)) [Ship_toCounty],
	cast([Ship-toCountry_RegionCode] as nvarchar(4000)) [Ship_toCountry_RegionCode],
	cast([ExitPoint] as nvarchar(4000)) [ExitPoint],
	cast([Sell-toCity] as nvarchar(4000)) [Sell_toCity],
	cast([Sell-toContact] as nvarchar(4000)) [Sell_toContact],
	cast([Bill-toPostCode] as nvarchar(4000)) [Bill_toPostCode],
	cast([Bill-toCounty] as nvarchar(4000)) [Bill_toCounty],
	cast([Bill-toCountry_RegionCode] as nvarchar(4000)) [Bill_toCountry_RegionCode],
	cast([Sell-toPostCode] as nvarchar(4000)) [Sell_toPostCode],
	cast([TransportMethod] as nvarchar(4000)) [TransportMethod],
	cast([VATCountry_RegionCode] as nvarchar(4000)) [VATCountry_RegionCode],
	cast([Sell-toCustomerName] as nvarchar(4000)) [Sell_toCustomerName],
	cast([Sell-toCustomerName2] as nvarchar(4000)) [Sell_toCustomerName2],
	cast([Sell-toAddress] as nvarchar(4000)) [Sell_toAddress],
	cast([Sell-toAddress2] as nvarchar(4000)) [Sell_toAddress2],
	cast([Applies-toDoc_No_] as nvarchar(4000)) [Applies_toDoc_No],
	cast([Bal_AccountNo_] as nvarchar(4000)) [Bal_AccountNo],
	cast([VATRegistrationNo_] as nvarchar(4000)) [VATRegistrationNo],
	cast([ReasonCode] as nvarchar(4000)) [ReasonCode],
	cast([Gen_Bus_PostingGroup] as nvarchar(4000)) [Gen_Bus_PostingGroup],
	cast([TransactionType] as nvarchar(4000)) [TransactionType],
	cast([CustomerPriceGroup] as nvarchar(4000)) [CustomerPriceGroup],
	cast([InvoiceDisc_Code] as nvarchar(4000)) [InvoiceDisc_Code],
	cast([CustomerDisc_Group] as nvarchar(4000)) [CustomerDisc_Group],
	cast([LanguageCode] as nvarchar(4000)) [LanguageCode],
	cast([SalespersonCode] as nvarchar(4000)) [SalespersonCode],
	cast([OnHold] as nvarchar(4000)) [OnHold],
	cast([ShipmentMethodCode] as nvarchar(4000)) [ShipmentMethodCode],
	cast([LocationCode] as nvarchar(4000)) [LocationCode],
	cast([ShortcutDimension1Code] as nvarchar(4000)) [ShortcutDimension1Code],
	cast([ShortcutDimension2Code] as nvarchar(4000)) [ShortcutDimension2Code],
	cast([CustomerPostingGroup] as nvarchar(4000)) [CustomerPostingGroup],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	cast([Ship-toAddress] as nvarchar(4000)) [Ship_toAddress],
	cast([Ship-toAddress2] as nvarchar(4000)) [Ship_toAddress2],
	cast([Ship-toCity] as nvarchar(4000)) [Ship_toCity],
	cast([Ship-toContact] as nvarchar(4000)) [Ship_toContact],
	cast([PostingDescription] as nvarchar(4000)) [PostingDescription],
	cast([PaymentTermsCode] as nvarchar(4000)) [PaymentTermsCode],
	cast([Bill-toCity] as nvarchar(4000)) [Bill_toCity],
	cast([Bill-toContact] as nvarchar(4000)) [Bill_toContact],
	cast([YourReference] as nvarchar(4000)) [YourReference],
	cast([Ship-toCode] as nvarchar(4000)) [Ship_toCode],
	cast([Ship-toName] as nvarchar(4000)) [Ship_toName],
	cast([Ship-toName2] as nvarchar(4000)) [Ship_toName2],
	cast([Sell-toCustomerNo_] as nvarchar(4000)) [Sell_toCustomerNo],
	cast([Bill-toCustomerNo_] as nvarchar(4000)) [Bill_toCustomerNo],
	cast([Bill-toName] as nvarchar(4000)) [Bill_toName],
	cast([Bill-toName2] as nvarchar(4000)) [Bill_toName2],
	cast([Bill-toAddress] as nvarchar(4000)) [Bill_toAddress],
	cast([Bill-toAddress2] as nvarchar(4000)) [Bill_toAddress2],
	[PostingDate] ,
	[ShipmentDate] ,
	[DueDate] ,
	[Pmt_DiscountDate] ,
	[DocumentDate] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[PricesIncludingVAT] ,
	[No_Printed] ,
	[DimensionSetID] ,
	[DocumentExchangeStatus] ,
	[Cust_LedgerEntryNo_] as [Cust_LedgerEntryNo],
	[AllowLineDisc_] as [AllowLineDisc],
	[GetReturnReceiptUsed] ,
	[ElectronicDocumentSent] ,
	[Applies-toDoc_Type] as [Applies_toDoc_Type],
	[EU3-PartyTrade] as [EU3_PartyTrade],
	[Bal_AccountType] ,
	[Correction] ,
	[TaxLiable] ,
	[PrepaymentCreditMemo] ,
	[No_ofE-DocumentsSent] as [No_ofE_DocumentsSent],
	[ElectronicDocumentStatus] ,
	[PriceCalculationMethod] ,
	[PaymentDiscount_] as [PaymentDiscount],
	[CurrencyFactor] ,
	[VATBaseDiscount_] as [VATBaseDiscount],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([OriginalDocumentXML] as nvarchar(4000)) [OriginalDocumentXML],
	cast([OriginalString] as nvarchar(4000)) [OriginalString],
	cast([DigitalStampSAT] as nvarchar(4000)) [DigitalStampSAT],
	cast([SignedDocumentXML] as nvarchar(4000)) [SignedDocumentXML],
	cast([DigitalStampPAC] as nvarchar(4000)) [DigitalStampPAC],
	cast([QRCode] as nvarchar(4000)) [QRCode],
	cast([WorkDescription] as nvarchar(4000)) [WorkDescription]
From stg.[BC_BJAuctionCompany_SalesCrMemoHeader_0972_Raw]
