{{ config(materialized='view',schema='stg')}}
Select
	[EntryNo_] as [EntryNo],
	cast([VendorNo_] as nvarchar(4000)) [VendorNo],
	cast([DocumentNo_] as nvarchar(4000)) [DocumentNo],
	cast([Description] as nvarchar(4000)) [Description],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	[ReversedEntryNo_] as [ReversedEntryNo],
	[Prepayment] ,
	[ExportedtoPaymentFile] ,
	[DimensionSetID] ,
	[Bal_AccountType] ,
	[TransactionNo_] as [TransactionNo],
	[AcceptedPmt_Disc_Tolerance] ,
	[ApplyingEntry] ,
	[Reversed] ,
	[ReversedbyEntryNo_] as [ReversedbyEntryNo],
	[DocumentType] ,
	[Applies-toDoc_Type] as [Applies_toDoc_Type],
	[Open] ,
	[Positive] ,
	[ClosedbyEntryNo_] as [ClosedbyEntryNo],
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[PostingDate] ,
	[DueDate] ,
	[Pmt_DiscountDate] ,
	[ClosedatDate] ,
	[DocumentDate] ,
	[Pmt_Disc_ToleranceDate] ,
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([VendorName] as nvarchar(4000)) [VendorName],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy],
	cast([PaymentReference] as nvarchar(4000)) [PaymentReference],
	cast([PaymentMethodCode] as nvarchar(4000)) [PaymentMethodCode],
	cast([Applies-toExt_Doc_No_] as nvarchar(4000)) [Applies_toExt_Doc_No],
	cast([RecipientBankAccount] as nvarchar(4000)) [RecipientBankAccount],
	cast([MessagetoRecipient] as nvarchar(4000)) [MessagetoRecipient],
	cast([IRS1099Code] as nvarchar(4000)) [IRS1099Code],
	cast([Bal_AccountNo_] as nvarchar(4000)) [Bal_AccountNo],
	cast([ExternalDocumentNo_] as nvarchar(4000)) [ExternalDocumentNo],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([ClosedbyCurrencyCode] as nvarchar(4000)) [ClosedbyCurrencyCode],
	cast([ICPartnerCode] as nvarchar(4000)) [ICPartnerCode],
	cast([CreditorNo_] as nvarchar(4000)) [CreditorNo],
	cast([SourceCode] as nvarchar(4000)) [SourceCode],
	cast([OnHold] as nvarchar(4000)) [OnHold],
	cast([Applies-toDoc_No_] as nvarchar(4000)) [Applies_toDoc_No],
	cast([Applies-toID] as nvarchar(4000)) [Applies_toID],
	cast([JournalBatchName] as nvarchar(4000)) [JournalBatchName],
	cast([ReasonCode] as nvarchar(4000)) [ReasonCode],
	cast([Buy-fromVendorNo_] as nvarchar(4000)) [Buy_fromVendorNo],
	cast([VendorPostingGroup] as nvarchar(4000)) [VendorPostingGroup],
	cast([GlobalDimension1Code] as nvarchar(4000)) [GlobalDimension1Code],
	cast([GlobalDimension2Code] as nvarchar(4000)) [GlobalDimension2Code],
	cast([PurchaserCode] as nvarchar(4000)) [PurchaserCode],
	cast([UserID] as nvarchar(4000)) [UserID],
	[Pmt_ToleranceLCY] ,
	[AmounttoApply] ,
	[IRS1099Amount] ,
	[ClosedbyCurrencyAmount] ,
	[AdjustedCurrencyFactor] ,
	[OriginalCurrencyFactor] ,
	[RemainingPmt_Disc_Possible] ,
	[Max_PaymentTolerance] ,
	[AcceptedPaymentTolerance] ,
	[PurchaseLCY] ,
	[Inv_DiscountLCY] ,
	[OriginalPmt_Disc_Possible] ,
	[Pmt_Disc_Rcd_LCY] ,
	[ClosedbyAmount] ,
	[ClosedbyAmountLCY] 
From stg.[BC_BJAuctionCompany_VendorLedgerEntry_0972_Raw]
