{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	[PaymentDiscount_] as [PaymentDiscount],
	[CurrencyFactor] ,
	[VATBaseDiscount_] as [VATBaseDiscount],
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[OrderDate] ,
	[PostingDate] ,
	[ExpectedReceiptDate] ,
	[DueDate] ,
	[Pmt_DiscountDate] ,
	[DocumentDate] ,
	[PricesIncludingVAT] ,
	[No_Printed] ,
	[Applies-toDoc_Type] as [Applies_toDoc_Type],
	[Bal_AccountType] ,
	[Correction] ,
	[TaxLiable] ,
	[PrepaymentInvoice] ,
	[DimensionSetID] ,
	[VendorLedgerEntryNo_] as [VendorLedgerEntryNo],
	[PriceCalculationMethod] ,
	[DIOT-TypeofOperation] as [DIOT_TypeofOperation],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([Id] as nvarchar(4000)) [Id],
	cast([Ship-toUPSZone] as nvarchar(4000)) [Ship_toUPSZone],
	cast([TaxExemptionNo_] as nvarchar(4000)) [TaxExemptionNo],
	cast([ProvincialTaxAreaCode] as nvarchar(4000)) [ProvincialTaxAreaCode],
	cast([STETransactionID] as nvarchar(4000)) [STETransactionID],
	cast([IRS1099Code] as nvarchar(4000)) [IRS1099Code],
	cast([CreditorNo_] as nvarchar(4000)) [CreditorNo],
	cast([PaymentReference] as nvarchar(4000)) [PaymentReference],
	cast([CampaignNo_] as nvarchar(4000)) [CampaignNo],
	cast([Buy-fromContactNo_] as nvarchar(4000)) [Buy_fromContactNo],
	cast([Pay-toContactNo_] as nvarchar(4000)) [Pay_toContactNo],
	cast([ResponsibilityCenter] as nvarchar(4000)) [ResponsibilityCenter],
	cast([SourceCode] as nvarchar(4000)) [SourceCode],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([PrepaymentNo_Series] as nvarchar(4000)) [PrepaymentNo_Series],
	cast([PrepaymentOrderNo_] as nvarchar(4000)) [PrepaymentOrderNo],
	cast([QuoteNo_] as nvarchar(4000)) [QuoteNo],
	cast([PaymentMethodCode] as nvarchar(4000)) [PaymentMethodCode],
	cast([Pre-AssignedNo_Series] as nvarchar(4000)) [Pre_AssignedNo_Series],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([OrderNo_Series] as nvarchar(4000)) [OrderNo_Series],
	cast([Pre-AssignedNo_] as nvarchar(4000)) [Pre_AssignedNo],
	cast([UserID] as nvarchar(4000)) [UserID],
	cast([Ship-toCounty] as nvarchar(4000)) [Ship_toCounty],
	cast([Ship-toCountry_RegionCode] as nvarchar(4000)) [Ship_toCountry_RegionCode],
	cast([OrderAddressCode] as nvarchar(4000)) [OrderAddressCode],
	cast([EntryPoint] as nvarchar(4000)) [EntryPoint],
	cast([Area] as nvarchar(4000)) [Area],
	cast([TransactionSpecification] as nvarchar(4000)) [TransactionSpecification],
	cast([Pay-toCounty] as nvarchar(4000)) [Pay_toCounty],
	cast([Pay-toCountry_RegionCode] as nvarchar(4000)) [Pay_toCountry_RegionCode],
	cast([Buy-fromPostCode] as nvarchar(4000)) [Buy_fromPostCode],
	cast([Buy-fromCounty] as nvarchar(4000)) [Buy_fromCounty],
	cast([Buy-fromCountry_RegionCode] as nvarchar(4000)) [Buy_fromCountry_RegionCode],
	cast([Ship-toPostCode] as nvarchar(4000)) [Ship_toPostCode],
	cast([Buy-fromVendorName2] as nvarchar(4000)) [Buy_fromVendorName2],
	cast([Buy-fromAddress] as nvarchar(4000)) [Buy_fromAddress],
	cast([Buy-fromAddress2] as nvarchar(4000)) [Buy_fromAddress2],
	cast([Buy-fromCity] as nvarchar(4000)) [Buy_fromCity],
	cast([Buy-fromContact] as nvarchar(4000)) [Buy_fromContact],
	cast([Pay-toPostCode] as nvarchar(4000)) [Pay_toPostCode],
	cast([ReasonCode] as nvarchar(4000)) [ReasonCode],
	cast([Gen_Bus_PostingGroup] as nvarchar(4000)) [Gen_Bus_PostingGroup],
	cast([TransactionType] as nvarchar(4000)) [TransactionType],
	cast([TransportMethod] as nvarchar(4000)) [TransportMethod],
	cast([VATCountry_RegionCode] as nvarchar(4000)) [VATCountry_RegionCode],
	cast([Buy-fromVendorName] as nvarchar(4000)) [Buy_fromVendorName],
	cast([Applies-toDoc_No_] as nvarchar(4000)) [Applies_toDoc_No],
	cast([Bal_AccountNo_] as nvarchar(4000)) [Bal_AccountNo],
	cast([VendorOrderNo_] as nvarchar(4000)) [VendorOrderNo],
	cast([VendorInvoiceNo_] as nvarchar(4000)) [VendorInvoiceNo],
	cast([VATRegistrationNo_] as nvarchar(4000)) [VATRegistrationNo],
	cast([Sell-toCustomerNo_] as nvarchar(4000)) [Sell_toCustomerNo],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	cast([InvoiceDisc_Code] as nvarchar(4000)) [InvoiceDisc_Code],
	cast([LanguageCode] as nvarchar(4000)) [LanguageCode],
	cast([PurchaserCode] as nvarchar(4000)) [PurchaserCode],
	cast([OrderNo_] as nvarchar(4000)) [OrderNo],
	cast([OnHold] as nvarchar(4000)) [OnHold],
	cast([PaymentTermsCode] as nvarchar(4000)) [PaymentTermsCode],
	cast([ShipmentMethodCode] as nvarchar(4000)) [ShipmentMethodCode],
	cast([LocationCode] as nvarchar(4000)) [LocationCode],
	cast([ShortcutDimension1Code] as nvarchar(4000)) [ShortcutDimension1Code],
	cast([ShortcutDimension2Code] as nvarchar(4000)) [ShortcutDimension2Code],
	cast([VendorPostingGroup] as nvarchar(4000)) [VendorPostingGroup],
	cast([Ship-toName2] as nvarchar(4000)) [Ship_toName2],
	cast([Ship-toAddress] as nvarchar(4000)) [Ship_toAddress],
	cast([Ship-toAddress2] as nvarchar(4000)) [Ship_toAddress2],
	cast([Ship-toCity] as nvarchar(4000)) [Ship_toCity],
	cast([Ship-toContact] as nvarchar(4000)) [Ship_toContact],
	cast([PostingDescription] as nvarchar(4000)) [PostingDescription],
	cast([Pay-toAddress2] as nvarchar(4000)) [Pay_toAddress2],
	cast([Pay-toCity] as nvarchar(4000)) [Pay_toCity],
	cast([Pay-toContact] as nvarchar(4000)) [Pay_toContact],
	cast([YourReference] as nvarchar(4000)) [YourReference],
	cast([Ship-toCode] as nvarchar(4000)) [Ship_toCode],
	cast([Ship-toName] as nvarchar(4000)) [Ship_toName],
	cast([Buy-fromVendorNo_] as nvarchar(4000)) [Buy_fromVendorNo],
	cast([Pay-toVendorNo_] as nvarchar(4000)) [Pay_toVendorNo],
	cast([Pay-toName] as nvarchar(4000)) [Pay_toName],
	cast([Pay-toName2] as nvarchar(4000)) [Pay_toName2],
	cast([Pay-toAddress] as nvarchar(4000)) [Pay_toAddress],
	cast([FiscalInvoiceNumberPAC] as nvarchar(4000)) [FiscalInvoiceNumberPAC],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([DraftInvoiceSystemId] as nvarchar(4000)) [DraftInvoiceSystemId],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy]
From stg.[BC_BJAuctionCompany_PurchInvHeader_0972_Raw]
