{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([EORINumber] as nvarchar(4000)) [EORINumber],
	cast([MobilePhoneNo_] as nvarchar(4000)) [MobilePhoneNo],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy],
	cast([TaxAreaID] as nvarchar(4000)) [TaxAreaID],
	cast([ContactID] as nvarchar(4000)) [ContactID],
	cast([ContactGraphId] as nvarchar(4000)) [ContactGraphId],
	cast([CFDIPurpose] as nvarchar(4000)) [CFDIPurpose],
	cast([CFDIRelation] as nvarchar(4000)) [CFDIRelation],
	cast([Ship-toCode] as nvarchar(4000)) [Ship_toCode],
	cast([Image] as nvarchar(4000)) [Image],
	cast([Id] as nvarchar(4000)) [Id],
	cast([CurrencyId] as nvarchar(4000)) [CurrencyId],
	cast([PaymentTermsId] as nvarchar(4000)) [PaymentTermsId],
	cast([ShipmentMethodId] as nvarchar(4000)) [ShipmentMethodId],
	cast([PaymentMethodId] as nvarchar(4000)) [PaymentMethodId],
	cast([TaxExemptionNo_] as nvarchar(4000)) [TaxExemptionNo],
	cast([RFCNo_] as nvarchar(4000)) [RFCNo],
	cast([CURPNo_] as nvarchar(4000)) [CURPNo],
	cast([StateInscription] as nvarchar(4000)) [StateInscription],
	cast([DocumentSendingProfile] as nvarchar(4000)) [DocumentSendingProfile],
	cast([GLN] as nvarchar(4000)) [GLN],
	cast([ResponsibilityCenter] as nvarchar(4000)) [ResponsibilityCenter],
	cast([ShippingTime] as nvarchar(4000)) [ShippingTime],
	cast([ShippingAgentServiceCode] as nvarchar(4000)) [ShippingAgentServiceCode],
	cast([ServiceZoneCode] as nvarchar(4000)) [ServiceZoneCode],
	cast([BaseCalendarCode] as nvarchar(4000)) [BaseCalendarCode],
	cast([UPSZone] as nvarchar(4000)) [UPSZone],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([ICPartnerCode] as nvarchar(4000)) [ICPartnerCode],
	cast([PreferredBankAccountCode] as nvarchar(4000)) [PreferredBankAccountCode],
	cast([CashFlowPaymentTermsCode] as nvarchar(4000)) [CashFlowPaymentTermsCode],
	cast([PrimaryContactNo_] as nvarchar(4000)) [PrimaryContactNo],
	cast([PostCode] as nvarchar(4000)) [PostCode],
	cast([County] as nvarchar(4000)) [County],
	cast([E-Mail] as nvarchar(4000)) [E_Mail],
	cast([HomePage] as nvarchar(4000)) [HomePage],
	cast([ReminderTermsCode] as nvarchar(4000)) [ReminderTermsCode],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([PaymentMethodCode] as nvarchar(4000)) [PaymentMethodCode],
	cast([LocationCode] as nvarchar(4000)) [LocationCode],
	cast([FaxNo_] as nvarchar(4000)) [FaxNo],
	cast([TelexAnswerBack] as nvarchar(4000)) [TelexAnswerBack],
	cast([VATRegistrationNo_] as nvarchar(4000)) [VATRegistrationNo],
	cast([Gen_Bus_PostingGroup] as nvarchar(4000)) [Gen_Bus_PostingGroup],
	cast([PlaceofExport] as nvarchar(4000)) [PlaceofExport],
	cast([InvoiceDisc_Code] as nvarchar(4000)) [InvoiceDisc_Code],
	cast([CustomerDisc_Group] as nvarchar(4000)) [CustomerDisc_Group],
	cast([Country_RegionCode] as nvarchar(4000)) [Country_RegionCode],
	cast([CollectionMethod] as nvarchar(4000)) [CollectionMethod],
	cast([Bill-toCustomerNo_] as nvarchar(4000)) [Bill_toCustomerNo],
	cast([LanguageCode] as nvarchar(4000)) [LanguageCode],
	cast([PaymentTermsCode] as nvarchar(4000)) [PaymentTermsCode],
	cast([Fin_ChargeTermsCode] as nvarchar(4000)) [Fin_ChargeTermsCode],
	cast([SalespersonCode] as nvarchar(4000)) [SalespersonCode],
	cast([ShipmentMethodCode] as nvarchar(4000)) [ShipmentMethodCode],
	cast([ShippingAgentCode] as nvarchar(4000)) [ShippingAgentCode],
	cast([GlobalDimension1Code] as nvarchar(4000)) [GlobalDimension1Code],
	cast([GlobalDimension2Code] as nvarchar(4000)) [GlobalDimension2Code],
	cast([ChainName] as nvarchar(4000)) [ChainName],
	cast([CustomerPostingGroup] as nvarchar(4000)) [CustomerPostingGroup],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	cast([CustomerPriceGroup] as nvarchar(4000)) [CustomerPriceGroup],
	cast([City] as nvarchar(4000)) [City],
	cast([Contact] as nvarchar(4000)) [Contact],
	cast([PhoneNo_] as nvarchar(4000)) [PhoneNo],
	cast([TelexNo_] as nvarchar(4000)) [TelexNo],
	cast([OurAccountNo_] as nvarchar(4000)) [OurAccountNo],
	cast([TerritoryCode] as nvarchar(4000)) [TerritoryCode],
	cast([Name] as nvarchar(4000)) [Name],
	cast([SearchName] as nvarchar(4000)) [SearchName],
	cast([Name2] as nvarchar(4000)) [Name2],
	cast([Address] as nvarchar(4000)) [Address],
	cast([Address2] as nvarchar(4000)) [Address2],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([Picture] as nvarchar(4000)) [Picture],
	[BudgetedAmount] ,
	[CreditLimitLCY] ,
	[Amount] ,
	[Prepayment_] as [Prepayment],
	[StatisticsGroup] ,
	[Blocked] ,
	[ContactType] ,
	[ValidateEUVatReg_No_] as [ValidateEUVatReg_No],
	[PrivacyBlocked] ,
	[DisableSearchbyName] ,
	[UseGLNinElectronicDocument] ,
	[PriceCalculationMethod] ,
	[AllowLineDisc_] as [AllowLineDisc],
	[CopySell-toAddr_toQteFrom] as [CopySell_toAddr_toQteFrom],
	[BankCommunication] ,
	[CheckDateFormat] ,
	[CheckDateSeparator] ,
	[TaxIdentificationType] ,
	[CombineShipments] ,
	[TaxLiable] ,
	[Reserve] ,
	[BlockPaymentTolerance] ,
	[PartnerType] ,
	[ShippingAdvice] ,
	[InvoiceCopies] ,
	[LastStatementNo_] as [LastStatementNo],
	[PrintStatements] ,
	[Priority] ,
	[ApplicationMethod] ,
	[PricesIncludingVAT] ,
	[LastDateModified] ,
	[LastModifiedDateTime] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt]
From stg.[BC_BJAuctionCompany_Customer_0972_Raw]
