{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	[BudgetedAmount] ,
	[Prepayment_] as [Prepayment],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([Picture] as nvarchar(4000)) [Picture],
	[LastDateModified] ,
	[LastModifiedDateTime] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[FATCAfilingrequirement] ,
	[ValidateEUVatReg_No_] as [ValidateEUVatReg_No],
	[PrivacyBlocked] ,
	[DisableSearchbyName] ,
	[PriceCalculationMethod] ,
	[DIOT-TypeofOperation] as [DIOT_TypeofOperation],
	[BlockPaymentTolerance] ,
	[PartnerType] ,
	[BankCommunication] ,
	[CheckDateFormat] ,
	[CheckDateSeparator] ,
	[TaxIdentificationType] ,
	[StatisticsGroup] ,
	[Blocked] ,
	[Priority] ,
	[ApplicationMethod] ,
	[PricesIncludingVAT] ,
	[TaxLiable] ,
	cast([PaymentTermsId] as nvarchar(4000)) [PaymentTermsId],
	cast([PaymentMethodId] as nvarchar(4000)) [PaymentMethodId],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([EORINumber] as nvarchar(4000)) [EORINumber],
	cast([MobilePhoneNo_] as nvarchar(4000)) [MobilePhoneNo],
	cast([Over-ReceiptCode] as nvarchar(4000)) [Over_ReceiptCode],
	cast([StateInscription] as nvarchar(4000)) [StateInscription],
	cast([GLN] as nvarchar(4000)) [GLN],
	cast([Image] as nvarchar(4000)) [Image],
	cast([DocumentSendingProfile] as nvarchar(4000)) [DocumentSendingProfile],
	cast([Id] as nvarchar(4000)) [Id],
	cast([CurrencyId] as nvarchar(4000)) [CurrencyId],
	cast([BaseCalendarCode] as nvarchar(4000)) [BaseCalendarCode],
	cast([UPSZone] as nvarchar(4000)) [UPSZone],
	cast([FederalIDNo_] as nvarchar(4000)) [FederalIDNo],
	cast([IRS1099Code] as nvarchar(4000)) [IRS1099Code],
	cast([RFCNo_] as nvarchar(4000)) [RFCNo],
	cast([CURPNo_] as nvarchar(4000)) [CURPNo],
	cast([PreferredBankAccountCode] as nvarchar(4000)) [PreferredBankAccountCode],
	cast([CashFlowPaymentTermsCode] as nvarchar(4000)) [CashFlowPaymentTermsCode],
	cast([PrimaryContactNo_] as nvarchar(4000)) [PrimaryContactNo],
	cast([ResponsibilityCenter] as nvarchar(4000)) [ResponsibilityCenter],
	cast([LocationCode] as nvarchar(4000)) [LocationCode],
	cast([LeadTimeCalculation] as nvarchar(4000)) [LeadTimeCalculation],
	cast([HomePage] as nvarchar(4000)) [HomePage],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([ICPartnerCode] as nvarchar(4000)) [ICPartnerCode],
	cast([CreditorNo_] as nvarchar(4000)) [CreditorNo],
	cast([TelexAnswerBack] as nvarchar(4000)) [TelexAnswerBack],
	cast([VATRegistrationNo_] as nvarchar(4000)) [VATRegistrationNo],
	cast([Gen_Bus_PostingGroup] as nvarchar(4000)) [Gen_Bus_PostingGroup],
	cast([PostCode] as nvarchar(4000)) [PostCode],
	cast([County] as nvarchar(4000)) [County],
	cast([E-Mail] as nvarchar(4000)) [E_Mail],
	cast([ShippingAgentCode] as nvarchar(4000)) [ShippingAgentCode],
	cast([InvoiceDisc_Code] as nvarchar(4000)) [InvoiceDisc_Code],
	cast([Country_RegionCode] as nvarchar(4000)) [Country_RegionCode],
	cast([Pay-toVendorNo_] as nvarchar(4000)) [Pay_toVendorNo],
	cast([PaymentMethodCode] as nvarchar(4000)) [PaymentMethodCode],
	cast([FaxNo_] as nvarchar(4000)) [FaxNo],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	cast([LanguageCode] as nvarchar(4000)) [LanguageCode],
	cast([PaymentTermsCode] as nvarchar(4000)) [PaymentTermsCode],
	cast([Fin_ChargeTermsCode] as nvarchar(4000)) [Fin_ChargeTermsCode],
	cast([PurchaserCode] as nvarchar(4000)) [PurchaserCode],
	cast([ShipmentMethodCode] as nvarchar(4000)) [ShipmentMethodCode],
	cast([TelexNo_] as nvarchar(4000)) [TelexNo],
	cast([OurAccountNo_] as nvarchar(4000)) [OurAccountNo],
	cast([TerritoryCode] as nvarchar(4000)) [TerritoryCode],
	cast([GlobalDimension1Code] as nvarchar(4000)) [GlobalDimension1Code],
	cast([GlobalDimension2Code] as nvarchar(4000)) [GlobalDimension2Code],
	cast([VendorPostingGroup] as nvarchar(4000)) [VendorPostingGroup],
	cast([Name2] as nvarchar(4000)) [Name2],
	cast([Address] as nvarchar(4000)) [Address],
	cast([Address2] as nvarchar(4000)) [Address2],
	cast([City] as nvarchar(4000)) [City],
	cast([Contact] as nvarchar(4000)) [Contact],
	cast([PhoneNo_] as nvarchar(4000)) [PhoneNo],
	cast([Name] as nvarchar(4000)) [Name],
	cast([SearchName] as nvarchar(4000)) [SearchName],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy]
From stg.[BC_BJAuctionCompany_Vendor_0972_Raw]
