{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	[PriceUnitConversion] ,
	[Type] ,
	[AllowInvoiceDisc_] as [AllowInvoiceDisc],
	[Critical] ,
	[SalesBlocked] ,
	[PurchasingBlocked] ,
	[ReorderingPolicy] ,
	[IncludeInventory] ,
	[ManufacturingPolicy] ,
	[CreatedFromNonstockItem] ,
	[UseCross-Docking] as [UseCross_Docking],
	[OrderTrackingPolicy] ,
	[AssemblyPolicy] ,
	[Low-LevelCode] as [Low_LevelCode],
	[InventoryValueZero] ,
	[DiscreteOrderQuantity] ,
	[FlushingMethod] ,
	[ReplenishmentSystem] ,
	[Blocked] ,
	[PriceIncludesVAT] ,
	[AutomaticExt_Texts] ,
	[Reserve] ,
	[StockoutWarning] ,
	[PreventNegativeInventory] ,
	[StatisticsGroup] ,
	[CommissionGroup] ,
	[Price_ProfitCalculation] ,
	[CostingMethod] ,
	[CostisAdjusted] ,
	[AllowOnlineAdjustment] ,
	[LastDateTimeModified] ,
	[LastDateModified] ,
	[LastTimeModified] ,
	[LastUnitCostCalc_Date] ,
	[LastCountingPeriodUpdate] ,
	[NextCountingStartDate] ,
	[NextCountingEndDate] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[UnitPrice] ,
	[Profit_] as [Profit],
	[UnitCost] ,
	[StandardCost] ,
	[LastDirectCost] ,
	[OverflowLevel] ,
	[Single-LevelMaterialCost] as [Single_LevelMaterialCost],
	[Single-LevelCapacityCost] as [Single_LevelCapacityCost],
	[Single-LevelSubcontrd_Cost] as [Single_LevelSubcontrd_Cost],
	[Single-LevelCap_OvhdCost] as [Single_LevelCap_OvhdCost],
	[Single-LevelMfg_OvhdCost] as [Single_LevelMfg_OvhdCost],
	[MinimumOrderQuantity] ,
	[MaximumOrderQuantity] ,
	[SafetyStockQuantity] ,
	[OrderMultiple] ,
	[RoundingPrecision] ,
	[DampenerQuantity] ,
	[BudgetedAmount] ,
	[BudgetProfit] ,
	[LotSize] ,
	[Rolled-upMaterialCost] as [Rolled_upMaterialCost],
	[Rolled-upCapacityCost] as [Rolled_upCapacityCost],
	[Scrap_] as [Scrap],
	[GrossWeight] ,
	[NetWeight] ,
	[UnitsperParcel] ,
	[UnitVolume] ,
	[DutyUnitConversion] ,
	[BudgetQuantity] ,
	[IndirectCost_] as [IndirectCost],
	[ReorderPoint] ,
	[MaximumInventory] ,
	[ReorderQuantity] ,
	[UnitListPrice] ,
	[DutyDue_] as [DutyDue],
	[OverheadRate] ,
	[Rolled-upSubcontractedCost] as [Rolled_upSubcontractedCost],
	[Rolled-upMfg_OvhdCost] as [Rolled_upMfg_OvhdCost],
	[Rolled-upCap_OverheadCost] as [Rolled_upCap_OverheadCost],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	cast([SATItemClassification] as nvarchar(4000)) [SATItemClassification],
	cast([RoutingNo_] as nvarchar(4000)) [RoutingNo],
	cast([ProductionBOMNo_] as nvarchar(4000)) [ProductionBOMNo],
	cast([CommonItemNo_] as nvarchar(4000)) [CommonItemNo],
	cast([ItemCategoryId] as nvarchar(4000)) [ItemCategoryId],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([Put-awayUnitofMeasureCode] as nvarchar(4000)) [Put_awayUnitofMeasureCode],
	cast([PhysInvtCountingPeriodCode] as nvarchar(4000)) [PhysInvtCountingPeriodCode],
	cast([Id] as nvarchar(4000)) [Id],
	cast([UnitofMeasureId] as nvarchar(4000)) [UnitofMeasureId],
	cast([TaxGroupId] as nvarchar(4000)) [TaxGroupId],
	cast([DutyClass] as nvarchar(4000)) [DutyClass],
	cast([ItemTrackingCode] as nvarchar(4000)) [ItemTrackingCode],
	cast([LotNos_] as nvarchar(4000)) [LotNos],
	cast([ExpirationCalculation] as nvarchar(4000)) [ExpirationCalculation],
	cast([WarehouseClassCode] as nvarchar(4000)) [WarehouseClassCode],
	cast([SpecialEquipmentCode] as nvarchar(4000)) [SpecialEquipmentCode],
	cast([Put-awayTemplateCode] as nvarchar(4000)) [Put_awayTemplateCode],
	cast([LotAccumulationPeriod] as nvarchar(4000)) [LotAccumulationPeriod],
	cast([DampenerPeriod] as nvarchar(4000)) [DampenerPeriod],
	cast([ManufacturerCode] as nvarchar(4000)) [ManufacturerCode],
	cast([ItemCategoryCode] as nvarchar(4000)) [ItemCategoryCode],
	cast([ProductGroupCode] as nvarchar(4000)) [ProductGroupCode],
	cast([ServiceItemGroup] as nvarchar(4000)) [ServiceItemGroup],
	cast([SerialNos_] as nvarchar(4000)) [SerialNos],
	cast([SafetyLeadTime] as nvarchar(4000)) [SafetyLeadTime],
	cast([SalesUnitofMeasure] as nvarchar(4000)) [SalesUnitofMeasure],
	cast([Purch_UnitofMeasure] as nvarchar(4000)) [Purch_UnitofMeasure],
	cast([TimeBucket] as nvarchar(4000)) [TimeBucket],
	cast([ReschedulingPeriod] as nvarchar(4000)) [ReschedulingPeriod],
	cast([VATProd_PostingGroup] as nvarchar(4000)) [VATProd_PostingGroup],
	cast([GlobalDimension1Code] as nvarchar(4000)) [GlobalDimension1Code],
	cast([GlobalDimension2Code] as nvarchar(4000)) [GlobalDimension2Code],
	cast([ApplicationWksh_UserID] as nvarchar(4000)) [ApplicationWksh_UserID],
	cast([GTIN] as nvarchar(4000)) [GTIN],
	cast([DefaultDeferralTemplateCode] as nvarchar(4000)) [DefaultDeferralTemplateCode],
	cast([VATBus_PostingGr_Price] as nvarchar(4000)) [VATBus_PostingGr_Price],
	cast([Gen_Prod_PostingGroup] as nvarchar(4000)) [Gen_Prod_PostingGroup],
	cast([Picture] as nvarchar(4000)) [Picture],
	cast([Country_RegionofOriginCode] as nvarchar(4000)) [Country_RegionofOriginCode],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([TaxGroupCode] as nvarchar(4000)) [TaxGroupCode],
	cast([DutyCode] as nvarchar(4000)) [DutyCode],
	cast([Durability] as nvarchar(4000)) [Durability],
	cast([FreightType] as nvarchar(4000)) [FreightType],
	cast([TariffNo_] as nvarchar(4000)) [TariffNo],
	cast([Country_RegionPurchasedCode] as nvarchar(4000)) [Country_RegionPurchasedCode],
	cast([BlockReason] as nvarchar(4000)) [BlockReason],
	cast([ShelfNo_] as nvarchar(4000)) [ShelfNo],
	cast([ItemDisc_Group] as nvarchar(4000)) [ItemDisc_Group],
	cast([VendorNo_] as nvarchar(4000)) [VendorNo],
	cast([VendorItemNo_] as nvarchar(4000)) [VendorItemNo],
	cast([LeadTimeCalculation] as nvarchar(4000)) [LeadTimeCalculation],
	cast([AlternativeItemNo_] as nvarchar(4000)) [AlternativeItemNo],
	cast([No_2] as nvarchar(4000)) [No_2],
	cast([Description] as nvarchar(4000)) [Description],
	cast([SearchDescription] as nvarchar(4000)) [SearchDescription],
	cast([Description2] as nvarchar(4000)) [Description2],
	cast([BaseUnitofMeasure] as nvarchar(4000)) [BaseUnitofMeasure],
	cast([InventoryPostingGroup] as nvarchar(4000)) [InventoryPostingGroup],
	cast([PurchasingCode] as nvarchar(4000)) [PurchasingCode],
	cast([Over-ReceiptCode] as nvarchar(4000)) [Over_ReceiptCode],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy]
From stg.[BC_BJAuctionCompany_Item_0972_Raw]
