{{ config(materialized='view',schema='stg')}}
Select
	cast([No_] as nvarchar(4000)) [No],
	[Amount] ,
	[AmountIncludingVAT] ,
	[InvoiceDiscountValue] ,
	[InvoiceDiscountAmount] ,
	[TotalTaxAmount] ,
	[SubtotalAmount] ,
	cast([timestamp] as nvarchar(4000)) [timestamp],
	[PostingDate] ,
	[DueDate] ,
	[DocumentDate] ,
	[LastModifiedDateTime] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[Posted] ,
	[DocumentType] ,
	[DiscountAppliedBeforeTax] ,
	[IsTest] ,
	[PricesIncludingVAT] ,
	[TaxLiable] ,
	[InvoiceDiscountCalculation] ,
	[LastEmailSentStatus] ,
	[Cust_LedgerEntryNo_] as [Cust_LedgerEntryNo],
	[Status] ,
	cast([Bill-toCounty] as nvarchar(4000)) [Bill_toCounty],
	cast([Bill-toCountry_RegionCode] as nvarchar(4000)) [Bill_toCountry_RegionCode],
	cast([Ship-toPostCode] as nvarchar(4000)) [Ship_toPostCode],
	cast([Ship-toCounty] as nvarchar(4000)) [Ship_toCounty],
	cast([Ship-toCountry_RegionCode] as nvarchar(4000)) [Ship_toCountry_RegionCode],
	cast([Sell-toPhoneNo_] as nvarchar(4000)) [Sell_toPhoneNo],
	cast([Ship-toName] as nvarchar(4000)) [Ship_toName],
	cast([Ship-toAddress] as nvarchar(4000)) [Ship_toAddress],
	cast([Ship-toAddress2] as nvarchar(4000)) [Ship_toAddress2],
	cast([Ship-toCity] as nvarchar(4000)) [Ship_toCity],
	cast([Ship-toContact] as nvarchar(4000)) [Ship_toContact],
	cast([Bill-toPostCode] as nvarchar(4000)) [Bill_toPostCode],
	cast([Bill-toName] as nvarchar(4000)) [Bill_toName],
	cast([Bill-toAddress] as nvarchar(4000)) [Bill_toAddress],
	cast([Bill-toAddress2] as nvarchar(4000)) [Bill_toAddress2],
	cast([Bill-toCity] as nvarchar(4000)) [Bill_toCity],
	cast([Bill-toContact] as nvarchar(4000)) [Bill_toContact],
	cast([Ship-toCode] as nvarchar(4000)) [Ship_toCode],
	cast([ContactGraphId] as nvarchar(4000)) [ContactGraphId],
	cast([CurrencyId] as nvarchar(4000)) [CurrencyId],
	cast([PaymentTermsId] as nvarchar(4000)) [PaymentTermsId],
	cast([ShipmentMethodId] as nvarchar(4000)) [ShipmentMethodId],
	cast([TaxAreaID] as nvarchar(4000)) [TaxAreaID],
	cast([Bill-toCustomerNo_] as nvarchar(4000)) [Bill_toCustomerNo],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([Sell-toContactNo_] as nvarchar(4000)) [Sell_toContactNo],
	cast([Id] as nvarchar(4000)) [Id],
	cast([CustomerId] as nvarchar(4000)) [CustomerId],
	cast([OrderId] as nvarchar(4000)) [OrderId],
	cast([Sell-toCity] as nvarchar(4000)) [Sell_toCity],
	cast([Sell-toContact] as nvarchar(4000)) [Sell_toContact],
	cast([Sell-toPostCode] as nvarchar(4000)) [Sell_toPostCode],
	cast([Sell-toCounty] as nvarchar(4000)) [Sell_toCounty],
	cast([Sell-toCountry_RegionCode] as nvarchar(4000)) [Sell_toCountry_RegionCode],
	cast([ExternalDocumentNo_] as nvarchar(4000)) [ExternalDocumentNo],
	cast([SalespersonCode] as nvarchar(4000)) [SalespersonCode],
	cast([OrderNo_] as nvarchar(4000)) [OrderNo],
	cast([VATRegistrationNo_] as nvarchar(4000)) [VATRegistrationNo],
	cast([Sell-toCustomerName] as nvarchar(4000)) [Sell_toCustomerName],
	cast([Sell-toAddress] as nvarchar(4000)) [Sell_toAddress],
	cast([Sell-toAddress2] as nvarchar(4000)) [Sell_toAddress2],
	cast([Sell-toCustomerNo_] as nvarchar(4000)) [Sell_toCustomerNo],
	cast([YourReference] as nvarchar(4000)) [YourReference],
	cast([PaymentTermsCode] as nvarchar(4000)) [PaymentTermsCode],
	cast([ShipmentMethodCode] as nvarchar(4000)) [ShipmentMethodCode],
	cast([CustomerPostingGroup] as nvarchar(4000)) [CustomerPostingGroup],
	cast([CurrencyCode] as nvarchar(4000)) [CurrencyCode],
	cast([Sell-toE-Mail] as nvarchar(4000)) [Sell_toE_Mail],
	cast([Bill-toCustomerId] as nvarchar(4000)) [Bill_toCustomerId],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy]
From stg.[BC_BJAuctionCompany_SalesInvoiceEntityAggregate_0972_Raw]
