{{ config(materialized='view',schema='stg')}}
Select
	[EntryNo_] as [EntryNo],
	cast([G_LAccountNo_] as nvarchar(4000)) [G_LAccountNo],
	cast([DocumentNo_] as nvarchar(4000)) [DocumentNo],
	cast([Description] as nvarchar(4000)) [Description],
	cast([Bal_AccountNo_] as nvarchar(4000)) [Bal_AccountNo],
	cast([No_Series] as nvarchar(4000)) [No_Series],
	cast([TaxAreaCode] as nvarchar(4000)) [TaxAreaCode],
	cast([TaxGroupCode] as nvarchar(4000)) [TaxGroupCode],
	cast([VATBus_PostingGroup] as nvarchar(4000)) [VATBus_PostingGroup],
	cast([VATProd_PostingGroup] as nvarchar(4000)) [VATProd_PostingGroup],
	cast([ICPartnerCode] as nvarchar(4000)) [ICPartnerCode],
	cast([JournalBatchName] as nvarchar(4000)) [JournalBatchName],
	cast([ReasonCode] as nvarchar(4000)) [ReasonCode],
	cast([Gen_Bus_PostingGroup] as nvarchar(4000)) [Gen_Bus_PostingGroup],
	cast([Gen_Prod_PostingGroup] as nvarchar(4000)) [Gen_Prod_PostingGroup],
	cast([ExternalDocumentNo_] as nvarchar(4000)) [ExternalDocumentNo],
	cast([SourceNo_] as nvarchar(4000)) [SourceNo],
	cast([GlobalDimension1Code] as nvarchar(4000)) [GlobalDimension1Code],
	cast([GlobalDimension2Code] as nvarchar(4000)) [GlobalDimension2Code],
	cast([UserID] as nvarchar(4000)) [UserID],
	cast([SourceCode] as nvarchar(4000)) [SourceCode],
	cast([JobNo_] as nvarchar(4000)) [JobNo],
	cast([BusinessUnitCode] as nvarchar(4000)) [BusinessUnitCode],
	cast([Prod_OrderNo_] as nvarchar(4000)) [Prod_OrderNo],
	cast([STETransactionID] as nvarchar(4000)) [STETransactionID],
	cast([$systemId] as nvarchar(4000)) [systemId],
	cast([$systemCreatedBy] as nvarchar(4000)) [systemCreatedBy],
	cast([$systemModifiedBy] as nvarchar(4000)) [systemModifiedBy],
	cast([timestamp] as nvarchar(4000)) [timestamp],
	[DocumentType] ,
	[System-CreatedEntry] as [System_CreatedEntry],
	[Amount] ,
	[Add_-CurrencyCreditAmount] as [Add__CurrencyCreditAmount],
	[Quantity] ,
	[VATAmount] ,
	[DebitAmount] ,
	[CreditAmount] ,
	[Additional-CurrencyAmount] as [Additional_CurrencyAmount],
	[Add_-CurrencyDebitAmount] as [Add__CurrencyDebitAmount],
	[PostingDate] ,
	[DocumentDate] ,
	[LastModifiedDateTime] ,
	[$systemCreatedAt] as [systemCreatedAt],
	[$systemModifiedAt] as [systemModifiedAt],
	[FAEntryType] ,
	[FAEntryNo_] as [FAEntryNo],
	[GST_HST] ,
	[UseTax] ,
	[CloseIncomeStatementDim_ID] ,
	[Reversed] ,
	[ReversedbyEntryNo_] as [ReversedbyEntryNo],
	[ReversedEntryNo_] as [ReversedEntryNo],
	[DimensionSetID] ,
	[Prior-YearEntry] as [Prior_YearEntry],
	[Gen_PostingType] ,
	[Bal_AccountType] ,
	[TransactionNo_] as [TransactionNo],
	[SourceType] ,
	[TaxLiable] 
From stg.[BC_BJAuctionCompany_GLEntry_0972_Raw]
