{{ config(materialized='table',schema='stg')}}
SELECT
	[Id] AS [ListingID],
	[CompanyId] AS [CompanyID],
	[ListingSourceFK],
	[CategoryId] AS [CategoryID],
	[ListingStatusID],
	[ProductType],
	[PriceTypeID],
	[Price],
	[City],
	[State],
	[ZipCode] AS [PostalCode],
	[Latitude],
	[Longitude],
	[IsFeaturedListing],
	[FeaturedUntil] AS [FeaturedUntilDate],
	[FeaturedOn] AS [FeaturedOnDate],
	[SalesforceLeadID],
	[SalesforceOpportunityID],
	[LastSalesforceActivityDate],
	[RenewalStatus],
	[RenewalToken],
	[Shuffle_DateExpiresUTC] AS [ShuffleExpiresDateUTC],
	[IsActive],
	[CreateDate] AS [Created],
	[ModifyDate] AS [ModifiedDate]
FROM [stg].[CC_Listing_FinalView]