{{ config(materialized='table',schema='dbo')}}

with updateData as (
    select 
    FTtmp.[Auctioneer_Skey], 
    FTtmp.[BlockSale_AuctionBidder_Skey],
    FTtmp.[Sale_AuctionBidder_Skey],
    FTtmp.[Consignor_Skey],
    FTtmp.[Item_Skey],
    FTstg.[temp_BlockSaleID_SaleID],
    FTstg.[BlockSaleID],
    FTstg.[BlockSaleAuctionBidderID],
    FTstg.[SaleAuctionBidderID],
    FTstg.[DocketID],
    FTstg.[AuctioneerID], 
    FTstg.[BlockSaleStatus],
    FTstg.[SaleStatus],
    FTstg.[HammerPrice],
    FTstg.[ActualSalePrice],
    FTstg.[BlockSaleBuyerCommPct],
    FTstg.[SaleBuyerCommPct],
    FTstg.[BlockSaleBuyerCommDollars],
    FTstg.[SaleBuyerCommDollars],
    FTstg.[BlockSaleCommPct],
    FTstg.[SaleCommPct],
    FTstg.[BlockSaleCommDollars],
    FTstg.[SaleCommDollars],
    FTstg.[BlockSaleComments],
    FTstg.[SaleComments],
    FTstg.[BlockSaleBuyerCommOverride],
    FTstg.[BlockSaleSellerCommOverride],
    FTstg.[BlockSaleRunDate],
    FTstg.[BlockSaleStateTaxDollars],
    FTstg.[SaleStateTaxDollars],
    FTstg.[BlockSaleStateTaxRate], 
    FTstg.[SaleStateTaxRate], 
    FTstg.[BlockSaleCountyTaxDollars],
    FTstg.[SaleCountyTaxDollars],
    FTstg.[BlockSaleCountyTaxRate], 
    FTstg.[SaleCountyTaxRate], 
    FTstg.[BlockSaleCityTaxDollars],
    FTstg.[SaleCityTaxDollars],
    FTstg.[BlockSaleCityTaxRate], 
    FTstg.[SaleCityTaxRate], 
    FTstg.[BlockSaleTaxOverride],
    FTstg.[BlockSaleTaxExemptCode],
    FTstg.[SaleTaxExemptCode],
    FTstg.[BlockSaleCreated],
    FTstg.[BlockSaleUpdateEventID],
    FTstg.[SaleID], 
    FTstg.[ShipDateVerified],
    FTstg.[CarrierID],
    FTstg.[BuyerCustomerAccountID],
    FTstg.[SellerCustomerAccountID],
    FTstg.[ShipToAddressID],
    FTstg.[ShipToContactID],
    FTstg.[BillOfLading],
    FTstg.[BillOfLadingText],
    FTstg.[BMA],
    FTstg.[Legacy],
    FTstg.[ShipDate],
    FTstg.[NAVISION],
    FTstg.[BuyerDealerID],
    FTstg.[SellerAddressID],
    FTstg.[SellerDealerID],
    FTstg.[AlternateSaleType],
    FTstg.[SteveCommDollars],
    FTstg.[SteveCommPct],
    FTstg.[AssiterCommDollars],
    FTstg.[AssiterCommPct],
    FTstg.[Arbitrated],
    FTstg.[AdjustmentReason],
    FTstg.[AdjustedByUserName],
    FTstg.[AdjustmentDate],
    FTstg.[CarrierName],
    FTstg.[HoldWire],
    FTstg.[SaleCreated],
    FTstg.[SaleUpdateEventID]
    from stg.Auct_AuctionSale_FT_tmp as FTtmp 
    join stg.Auct_AuctionSale_FT_stg as FTstg 
    on FTstg.temp_BlockSaleID_SaleID=FTtmp.temp_BlockSaleID_SaleID
),
insertData as (
    select 
        [Auctioneer_Skey], 
        [BlockSale_AuctionBidder_Skey],
        [Sale_AuctionBidder_Skey],
        [Consignor_Skey],
        [Item_Skey],
        [temp_BlockSaleID_SaleID],
        [BlockSaleID],
        [BlockSaleAuctionBidderID],
        [SaleAuctionBidderID],
        [DocketID],
        [AuctioneerID], 
        [BlockSaleStatus],
        [SaleStatus],
        [HammerPrice],
        [ActualSalePrice],
        [BlockSaleBuyerCommPct],
        [SaleBuyerCommPct],
        [BlockSaleBuyerCommDollars],
        [SaleBuyerCommDollars],
        [BlockSaleCommPct],
        [SaleCommPct],
        [BlockSaleCommDollars],
        [SaleCommDollars],
        [BlockSaleComments],
        [SaleComments],
        [BlockSaleBuyerCommOverride],
        [BlockSaleSellerCommOverride],
        [BlockSaleRunDate],
        [BlockSaleStateTaxDollars],
        [SaleStateTaxDollars],
        [BlockSaleStateTaxRate], 
        [SaleStateTaxRate], 
        [BlockSaleCountyTaxDollars],
        [SaleCountyTaxDollars],
        [BlockSaleCountyTaxRate], 
        [SaleCountyTaxRate], 
        [BlockSaleCityTaxDollars],
        [SaleCityTaxDollars],
        [BlockSaleCityTaxRate], 
        [SaleCityTaxRate], 
        [BlockSaleTaxOverride],
        [BlockSaleTaxExemptCode],
        [SaleTaxExemptCode],
        [BlockSaleCreated],
        [BlockSaleUpdateEventID],
        [SaleID], 
        [ShipDateVerified],
        [CarrierID],
        [BuyerCustomerAccountID],
        [SellerCustomerAccountID],
        [ShipToAddressID],
        [ShipToContactID],
        [BillOfLading],
        [BillOfLadingText],
        [BMA],
        [Legacy],
        [ShipDate],
        [NAVISION],
        [BuyerDealerID],
        [SellerAddressID],
        [SellerDealerID],
        [AlternateSaleType],
        [SteveCommDollars],
        [SteveCommPct],
        [AssiterCommDollars],
        [AssiterCommPct],
        [Arbitrated],
        [AdjustmentReason],
        [AdjustedByUserName],
        [AdjustmentDate],
        [CarrierName],
        [HoldWire],
        [SaleCreated],
        [SaleUpdateEventID]
    from stg.Auct_AuctionSale_FT_tmp
    where temp_BlockSaleID_SaleID not in (select  temp_BlockSaleID_SaleID from stg.Auct_AuctionSale_FT_stg)
)
SELECT
    [BlockSale_AuctionBidder_Skey],
    [Sale_AuctionBidder_Skey],
    [Consignor_Skey],
    -- [BlockSaleID],
    -- [BlockSaleAuctionBidderID],
    -- [SaleAuctionBidderID],
    -- [DocketID],
    -- [AuctioneerID],
    [Auctioneer_Skey], 
    -- [Item_Skey],
    -- [SaleStatusID_BlockSale],
    [BlockSaleStatus],
    -- [SaleStatusID_Sale],
    [SaleStatus],
    [HammerPrice],
    [ActualSalePrice],
    [BlockSaleBuyerCommPct],
    [SaleBuyerCommPct],
    [BlockSaleBuyerCommDollars],
    [SaleBuyerCommDollars],
    [BlockSaleCommPct],
    [SaleCommPct],
    [BlockSaleCommDollars],
    [SaleCommDollars],
    [BlockSaleComments],
    [SaleComments],
    [BlockSaleBuyerCommOverride],
    [BlockSaleSellerCommOverride],
    [BlockSaleRunDate],
    [BlockSaleStateTaxDollars],
    [SaleStateTaxDollars],
    [BlockSaleStateTaxRate], 
    [SaleStateTaxRate], 
    [BlockSaleCountyTaxDollars],
    [SaleCountyTaxDollars],
    [BlockSaleCountyTaxRate], 
    [SaleCountyTaxRate], 
    [BlockSaleCityTaxDollars],
    [SaleCityTaxDollars],
    [BlockSaleCityTaxRate], 
    [SaleCityTaxRate], 
    [BlockSaleTaxOverride],
    [BlockSaleTaxExemptCode],
    [SaleTaxExemptCode],
    [BlockSaleCreated],
    [BlockSaleUpdateEventID],
    [SaleID], 
    [ShipDateVerified],
    [CarrierID],
    -- [BuyerCustomerAccountID],
    -- [SellerCustomerAccountID],
    [ShipToAddressID],
    [ShipToContactID],
    [BillOfLading],
    [BillOfLadingText],
    [BMA],
    [Legacy],
    [ShipDate],
    [NAVISION],
    [BuyerDealerID],
    [SellerAddressID],
    [SellerDealerID],
    [AlternateSaleType],
    [SteveCommDollars],
    [SteveCommPct],
    [AssiterCommDollars],
    [AssiterCommPct],
    [Arbitrated],
    [AdjustmentReason],
    [AdjustedByUserName],
    [AdjustmentDate],
    [CarrierName],
    [HoldWire],
    [SaleCreated],
    [SaleUpdateEventID]
from updateData
union all

SELECT
    [BlockSale_AuctionBidder_Skey],
    [Sale_AuctionBidder_Skey],
    [Consignor_Skey],
    -- [BlockSaleID],
    -- [BlockSaleAuctionBidderID],
    -- [SaleAuctionBidderID],
    -- [DocketID],
    -- [AuctioneerID],
    [Auctioneer_Skey], 
    -- [Item_Skey],
    -- [SaleStatusID_BlockSale],
    [BlockSaleStatus],
    -- [SaleStatusID_Sale],
    [SaleStatus],
    [HammerPrice],
    [ActualSalePrice],
    [BlockSaleBuyerCommPct],
    [SaleBuyerCommPct],
    [BlockSaleBuyerCommDollars],
    [SaleBuyerCommDollars],
    [BlockSaleCommPct],
    [SaleCommPct],
    [BlockSaleCommDollars],
    [SaleCommDollars],
    [BlockSaleComments],
    [SaleComments],
    [BlockSaleBuyerCommOverride],
    [BlockSaleSellerCommOverride],
    [BlockSaleRunDate],
    [BlockSaleStateTaxDollars],
    [SaleStateTaxDollars],
    [BlockSaleStateTaxRate], 
    [SaleStateTaxRate], 
    [BlockSaleCountyTaxDollars],
    [SaleCountyTaxDollars],
    [BlockSaleCountyTaxRate], 
    [SaleCountyTaxRate], 
    [BlockSaleCityTaxDollars],
    [SaleCityTaxDollars],
    [BlockSaleCityTaxRate], 
    [SaleCityTaxRate], 
    [BlockSaleTaxOverride],
    [BlockSaleTaxExemptCode],
    [SaleTaxExemptCode],
    [BlockSaleCreated],
    [BlockSaleUpdateEventID],
    [SaleID], 
    [ShipDateVerified],
    [CarrierID],
    -- [BuyerCustomerAccountID],
    -- [SellerCustomerAccountID],
    [ShipToAddressID],
    [ShipToContactID],
    [BillOfLading],
    [BillOfLadingText],
    [BMA],
    [Legacy],
    [ShipDate],
    [NAVISION],
    [BuyerDealerID],
    [SellerAddressID],
    [SellerDealerID],
    [AlternateSaleType],
    [SteveCommDollars],
    [SteveCommPct],
    [AssiterCommDollars],
    [AssiterCommPct],
    [Arbitrated],
    [AdjustmentReason],
    [AdjustedByUserName],
    [AdjustmentDate],
    [CarrierName],
    [HoldWire],
    [SaleCreated],
    [SaleUpdateEventID]
from insertData